'use client'
import { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'

type Mode = 'original' | 'bone' | 'heatmap'

interface ImagingEntry {
  modality: string
  region: string
  src: string
  enhanced?: string
  bone?: string
  heatmap?: string
}

interface Props {
  image: ImagingEntry
  onClose: () => void
}

interface RefChip {
  label: string
  href: string
}

interface ModeConfig {
  label: string
  badge: string
  description: string
  note: string
  refs: RefChip[]
}

const MODES: Record<Mode, ModeConfig> = {
  original: {
    label: 'Original',
    badge: 'Source',
    description: 'Standard clinical display at native resolution and grayscale windowing — exactly as captured by the imaging system.',
    note: 'No processing applied. Pixel values represent raw detector output.',
    refs: [],
  },
  bone: {
    label: 'Bone Window',
    badge: 'Density Map',
    description: 'False-color density mapping applied directly to pixel intensity values. Black = air/void, amber/orange = soft tissue, white = dense cortical bone. Gradients and subtle cortical irregularities invisible in standard grayscale become apparent under false color.',
    note: 'Derived from scan pixel data only — not from your medical record.',
    refs: [
      { label: 'Hounsfield Units', href: 'https://radiopaedia.org/articles/hounsfield-unit' },
      { label: 'matplotlib colormaps', href: 'https://matplotlib.org/stable/users/explain/colors/colormaps.html' },
    ],
  },
  heatmap: {
    label: 'AI Attention',
    badge: 'GradCAM',
    description: 'Gradient-weighted Class Activation Map (GradCAM) generated by a DenseNet-121 model trained on 112,120 chest radiographs across 14 pathology classes. Warm regions (red/yellow) indicate areas the model weights as clinically significant based on density pattern recognition — independent of any diagnosis in your record.',
    note: 'Applied to this scan image only — not derived from your health record or conditions.',
    refs: [
      { label: 'TorchXRayVision', href: 'https://github.com/mlmed/torchxrayvision' },
      { label: 'GradCAM (Selvaraju et al.)', href: 'https://arxiv.org/abs/1610.02391' },
      { label: 'CheXNet (Rajpurkar et al.)', href: 'https://arxiv.org/abs/1711.05225' },
    ],
  },
}

const SR_REFS: RefChip[] = [
  { label: 'Real-ESRGAN', href: 'https://github.com/xinntao/Real-ESRGAN' },
  { label: 'arXiv 2107.10833', href: 'https://arxiv.org/abs/2107.10833' },
]

export function ScanModal({ image, onClose }: Props) {
  const [mode, setMode] = useState<Mode>('original')

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const src =
    mode === 'bone'    ? (image.bone    ?? image.src) :
    mode === 'heatmap' ? (image.heatmap ?? image.src) :
                         image.src

  const cfg = MODES[mode]
  const isEnhanced = mode === 'original' && !!image.enhanced

  return createPortal(
    <div className="fixed inset-0 z-[60] flex items-center justify-center">
      <div className="absolute inset-0 bg-black/65 backdrop-blur-sm" onClick={onClose} />

      <div className="relative glass-panel backdrop-blur-[40px] backdrop-saturate-150 w-[clamp(460px,58vw,780px)] flex flex-col overflow-hidden">

        {/* header */}
        <div className="flex items-center justify-between px-5 pt-4 pb-3 border-b border-white/[0.06] shrink-0">
          <div className="flex items-center gap-2">
            <span className="px-1.5 py-0.5 text-[9px] font-[500] bg-white/10 text-white/55 rounded-full">
              {image.modality}
            </span>
            <span className="text-[13px] font-[300] text-white/80 tracking-tight">
              {image.region}
            </span>
          </div>
          <button
            onClick={onClose}
            className="text-white/25 hover:text-white/70 transition-colors text-[20px] leading-none w-7 h-7 flex items-center justify-center"
          >
            ×
          </button>
        </div>

        {/* image */}
        <div className="relative bg-black/50 flex items-center justify-center h-[clamp(260px,42vh,480px)] shrink-0">
          <img key={src} src={src} alt={image.region} className="max-w-full max-h-full object-contain" />
        </div>

        {/* mode tabs */}
        <div className="flex border-b border-white/[0.06] shrink-0">
          {(Object.keys(MODES) as Mode[]).map(m => {
            const available = m === 'original' ? true : m === 'bone' ? !!image.bone : !!image.heatmap
            return (
              <button
                key={m}
                onClick={() => available && setMode(m)}
                className={`flex-1 py-2.5 text-[11px] font-[300] transition-colors border-b-2 -mb-px ${
                  !available
                    ? 'text-white/15 border-transparent cursor-not-allowed'
                    : mode === m
                    ? 'text-white/85 border-lime'
                    : 'text-white/40 border-transparent hover:text-white/65'
                }`}
              >
                {MODES[m].label}
              </button>
            )
          })}
        </div>

        {/* description area */}
        <div className="px-5 py-4 flex flex-col gap-3 shrink-0">
          <div className="flex items-center gap-2">
            <span className="text-[9px] font-[500] uppercase tracking-widest text-white/30">{cfg.badge}</span>
            {mode === 'original' && image.enhanced && (
              <span className="text-[9px] font-[300] text-white/20">· SR-enhanced version available in other tabs</span>
            )}
          </div>

          <p className="text-[12px] font-[300] text-white/65 leading-relaxed">
            {cfg.description}
          </p>

          {cfg.note && (
            <p className="text-[10px] font-[300] text-lime/50 leading-relaxed">
              {cfg.note}
            </p>
          )}

          {/* refs */}
          {(mode === 'original' ? SR_REFS : cfg.refs).length > 0 && (
            <div className="flex flex-wrap gap-1.5 pt-0.5">
              {(mode === 'original' && image.enhanced
                ? SR_REFS
                : cfg.refs
              ).map(ref => (
                <a
                  key={ref.href}
                  href={ref.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2.5 py-1 text-[9px] font-[300] text-white/40 border border-white/10 rounded-full hover:text-lime/80 hover:border-lime/30 transition-colors"
                >
                  {ref.label} ↗
                </a>
              ))}
            </div>
          )}
        </div>

      </div>
    </div>,
    document.body
  )
}
